name: Upload Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    runs-on: [self-hosted]
    name: Publish release to PyPI
    #runs-on: ubuntu-latest
    # Specify the environment name you configured in PyPI (optional)
    environment:
      name: pypi
      url: https://pypi.org/p/pachinkoagentic # Replace with your project URL
    permissions:
      # This permission is required for the OIDC token exchange
      id-token: write
    defaults:
      run:
        working-directory: pachinkoagentic
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install 'build' to create distribution packages (wheels and sdists)
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package distributions to PyPI
        # Uses the trusted PyPA action for authentication and upload
        uses: pypa/gh-action-pypi-publish@release/v1

